version: '3.8'

services:
  galabau-fortkamp:
    image: localhost:5000/galabau-fortkamp:latest
    networks:
      - webproxy
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      labels:
        # Traefik aktivieren
        - "traefik.enable=true"
        
        # HTTP Router
        - "traefik.http.routers.galabau.rule=Host(`test.danapfel-digital.de`)"
        - "traefik.http.routers.galabau.entrypoints=web"
        
        # HTTPS Router
        - "traefik.http.routers.galabau-secure.rule=Host(`test.danapfel-digital.de`)"
        - "traefik.http.routers.galabau-secure.entrypoints=websecure"
        - "traefik.http.routers.galabau-secure.tls=true"
        - "traefik.http.routers.galabau-secure.tls.certresolver=letsencrypt"
        
        # HTTP zu HTTPS Redirect
        - "traefik.http.middlewares.galabau-redirect.redirectscheme.scheme=https"
        - "traefik.http.middlewares.galabau-redirect.redirectscheme.permanent=true"
        - "traefik.http.routers.galabau.middlewares=galabau-redirect"
        
        # Service Port (wichtig für Swarm!)
        - "traefik.http.services.galabau.loadbalancer.server.port=80"
        
        # Security Headers
        - "traefik.http.middlewares.galabau-headers.headers.customResponseHeaders.X-Robots-Tag=index,follow"
        - "traefik.http.middlewares.galabau-headers.headers.sslRedirect=true"
        - "traefik.http.middlewares.galabau-headers.headers.stsSeconds=31536000"
        - "traefik.http.middlewares.galabau-headers.headers.stsIncludeSubdomains=true"
        - "traefik.http.middlewares.galabau-headers.headers.stsPreload=true"
        - "traefik.http.routers.galabau-secure.middlewares=galabau-headers"

networks:
  webproxy:
    external: true

