version: '3.8'

services:
  web:
    image: 10.1.9.0:5000/galabau-fortkamp.de:latest
    environment:
      - S3_ENDPOINT=https://nbg1.your-objectstorage.com
      - S3_REGION=eu-central
      - S3_BUCKET=danapfel-digital
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - SMTP_HOST=mail.danapfel-digital.de
      - SMTP_PORT=465
      - SMTP_USER=info@galabau-fortkamp.de
      - SMTP_PASS=medion1997!
    networks:
      - public-ingress
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      labels:
        # Traefik aktivieren
        - "traefik.enable=true"

        # HTTPS Router (nur Hauptdomain, kein www)
        - "traefik.http.routers.galabau-fortkamp-de.rule=Host(`galabau-fortkamp.de`)"
        - "traefik.http.routers.galabau-fortkamp-de.entrypoints=websecure"
        - "traefik.http.routers.galabau-fortkamp-de.tls=true"
        - "traefik.http.routers.galabau-fortkamp-de.tls.certresolver=myresolver"

        # Service Port (Node.js auf Port 4321)
        - "traefik.http.services.galabau-fortkamp-de.loadbalancer.server.port=4321"

networks:
  public-ingress:
    external: true
